import React,{useEffect,useState}from'react';import{Routes,Route,Navigate,Link,useNavigate}from'react-router-dom';import{api,BASE}from'./api';import Bills from './Bills';
const money=n=>'₹'+Number(n||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2});
function App(){
 const [user,setUser]=useState(()=>JSON.parse(localStorage.getItem('user')||'null'));
 const [page,setPage]=useState('dashboard');const nav=useNavigate();
 async function logout(){try{await api('/auth/logout',{method:'POST'});}finally{localStorage.clear();setUser(null);nav('/login');}}
 if(!user)return <Routes><Route path="*" element={<Login onLogin={u=>setUser(u)}/>}/></Routes>;
 return <div className="app-shell"><aside className="sidebar"><div className="brand">🪔 Ganesh Fund</div><div className="small text-white-50 mb-4">Festival Management</div>
 {['dashboard','donations','expenses','bills',...(user.role==='ADMIN'?['users','logs']:[])].map(p=><button key={p} className={`side-link ${page===p?'active':''}`} onClick={()=>setPage(p)}>{({dashboard:'▦ Dashboard',donations:'♥ Donations',expenses:'₹ Expenses',bills:'▤ Bills & Receipts',users:'♙ User Management',logs:'◷ Activity Logs'})[p]}</button>)}
 <div className="sidebar-bottom"><div className="fw-semibold">{user.name}</div><span className="badge bg-warning text-dark">{user.role}</span><button className="btn btn-sm btn-outline-light mt-3 w-100" onClick={logout}>Logout</button></div></aside>
 <main className="main-area"><header className="topbar"><div><div className="text-secondary small">GANESH FESTIVAL / {page.toUpperCase()}</div><h4 className="mb-0">{({dashboard:'Financial Overview',donations:'Donations',expenses:'Expenses',bills:'Bills & Receipts',users:'User Management',logs:'Activity Logs'})[page]}</h4></div><span className="text-muted">Namaste, {user.name}</span></header>
 {page==='dashboard'?<Dashboard/>:page==='donations'?<Records type="donations" admin={user.role==='ADMIN'}/>:page==='expenses'?<Records type="expenses" admin={user.role==='ADMIN'}/>:page==='bills'?<Bills admin={user.role==='ADMIN'}/>:page==='users'?<Users/>:<Logs/>}
 </main></div>
}
function Login({onLogin}){const[email,setEmail]=useState('admin@ganesh.local'),[password,setPassword]=useState(''),[err,setErr]=useState('');
 async function submit(e){e.preventDefault();try{const d=await api('/auth/login',{method:'POST',body:JSON.stringify({email,password})});localStorage.setItem('token',d.token);localStorage.setItem('user',JSON.stringify(d.user));onLogin(d.user);}catch(e){setErr(e.message)}}
 return <div className="login-bg"><form className="login-card" onSubmit={submit}><div className="display-5 text-center">🪔</div><h3 className="text-center mt-2">Ganesh Festival Fund</h3><p className="text-center text-muted">Secure fund management portal</p>{err&&<div className="alert alert-danger">{err}</div>}<label>Email</label><input className="form-control mb-3" type="email" value={email} onChange={e=>setEmail(e.target.value)} required/><label>Password</label><input className="form-control mb-4" type="password" value={password} onChange={e=>setPassword(e.target.value)} required/><button className="btn btn-primary w-100">Sign in</button><div className="small text-muted mt-3">Initial demo credentials are shown in README. Change them before real use.</div></form></div>}
function Dashboard(){const[d,setD]=useState(null),[err,setErr]=useState('');useEffect(()=>{api('/dashboard').then(setD).catch(e=>setErr(e.message))},[]);if(err)return <div className="alert alert-danger">{err}</div>;if(!d)return <p>Loading dashboard…</p>;return <><div className="welcome"><h5>🙏 Jai Shri Ganesh</h5><div className="text-muted">A transparent view of your festival funds.</div></div><div className="row g-3 mt-1">{[['Total Donations',money(d.totalDonations),'green'],['Total Expenses',money(d.totalExpenses),'orange'],['Available Balance',money(d.balance),'blue'],['Donation Records',d.donationCount,'purple']].map(([t,v,c])=><div className="col-md-6 col-xl-3" key={t}><div className="stat-card"><div className={`stat-icon ${c}`}>₹</div><div className="text-muted small">{t}</div><div className="stat-value">{v}</div></div></div>)}</div><div className="card border-0 shadow-sm mt-4"><div className="card-body"><h5>Fund Summary</h5><p className="text-muted mb-2">Balance = total donations − total expenses</p><div className="progress" style={{height:12}}><div className="progress-bar bg-success" style={{width:`${Math.min(100,Math.max(0,Number(d.totalDonations)?Number(d.totalDonations)/(Number(d.totalDonations)+Number(d.totalExpenses))*100:0))}%`}}/></div><div className="d-flex justify-content-between small mt-2"><span>Donations {money(d.totalDonations)}</span><span>Expenses {money(d.totalExpenses)}</span></div></div></div></>}
function Records({type,admin}){const[rows,setRows]=useState([]),[err,setErr]=useState(''),[editing,setEditing]=useState(null),[show,setShow]=useState(false);const donation=type==='donations';const fields=donation?['donor_name','amount','donation_date','payment_method','transaction_id','receipt_number','notes']:['title','category','amount','expense_date','paid_to','payment_method','bill_number','description'];const labels={donor_name:'Donor name',amount:'Amount (₹)',donation_date:'Date',payment_method:'Payment method',transaction_id:'Transaction ID',receipt_number:'Receipt number',notes:'Notes',title:'Expense title',category:'Category',expense_date:'Date',paid_to:'Paid to',bill_number:'Bill number',description:'Description'};
 async function load(){try{setRows(await api('/'+type))}catch(e){setErr(e.message)}}useEffect(()=>{load()},[type]);
 async function save(e){e.preventDefault();const fd=new FormData(e.target),obj=Object.fromEntries(fd.entries());obj.amount=Number(obj.amount);try{await api(`/${type}${editing?'/'+editing.id:''}`,{method:editing?'PUT':'POST',body:JSON.stringify(obj)});setShow(false);setEditing(null);load()}catch(e){setErr(e.message)}}
 async function del(r){if(!confirm('Delete this record? This action will be logged.'))return;try{await api(`/${type}/${r.id}`,{method:'DELETE'});load()}catch(e){setErr(e.message)}}
 return <><div className="d-flex justify-content-between align-items-center mb-3"><div className="text-muted">Track and review all {type}.</div>{admin&&<button className="btn btn-primary" onClick={()=>{setEditing(null);setShow(true)}}>＋ Add {donation?'Donation':'Expense'}</button>}</div>{err&&<div className="alert alert-danger">{err}</div>}<div className="card border-0 shadow-sm table-responsive"><table className="table align-middle mb-0"><thead><tr>{(donation?['Donor','Amount','Date','Payment','Added by','Added on','Actions']:['Expense','Category','Amount','Date','Added by','Added on','Updated by','Actions']).map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id}>{donation?<><td><b>{r.donor_name}</b><div className="small text-muted">{r.receipt_number}</div></td><td className="fw-semibold">{money(r.amount)}</td><td>{String(r.donation_date).slice(0,10)}</td><td>{r.payment_method}</td><td>{r.created_by_name||'—'}</td><td>{new Date(r.created_at).toLocaleString()}</td></>:<><td><b>{r.title}</b><div className="small text-muted">{r.paid_to}</div></td><td>{r.category}</td><td className="fw-semibold">{money(r.amount)}</td><td>{String(r.expense_date).slice(0,10)}</td><td>{r.created_by_name||'—'}</td><td>{new Date(r.created_at).toLocaleString()}</td><td>{r.updated_by_name||'—'}</td></>}<td>{admin&&<><button className="btn btn-sm btn-outline-primary me-1" onClick={()=>{setEditing(r);setShow(true)}}>Edit</button><button className="btn btn-sm btn-outline-danger" onClick={()=>del(r)}>Delete</button></>}</td></tr>)}</tbody></table>{!rows.length&&<div className="p-4 text-center text-muted">No records yet.</div>}</div>
 {show&&<div className="modal-backdrop-custom"><form className="form-modal" onSubmit={save}><div className="d-flex justify-content-between"><h5>{editing?'Edit':'Add'} {donation?'Donation':'Expense'}</h5><button type="button" className="btn-close" onClick={()=>setShow(false)}/></div><div className="row g-3 mt-1">{fields.map(f=><div className={`col-md-${['notes','description'].includes(f)?12:6}`} key={f}><label className="form-label">{labels[f]}</label>{['notes','description'].includes(f)?<textarea className="form-control" name={f} defaultValue={editing?.[f]||''}/>:<input className="form-control" name={f} type={f.includes('date')?'date':f==='amount'?'number':'text'} step={f==='amount'?'0.01':undefined} min={f==='amount'?'0.01':undefined} required={['amount',donation?'donor_name':'title',donation?'donation_date':'expense_date'].includes(f)} defaultValue={editing?.[f]?(f.includes('date')?String(editing[f]).slice(0,10):editing[f]):(f.includes('date')?new Date().toISOString().slice(0,10):'')}/>}</div>)}</div><div className="text-end mt-4"><button type="button" className="btn btn-light me-2" onClick={()=>setShow(false)}>Cancel</button><button className="btn btn-primary">Save record</button></div></form></div>}</>}
function BillsLegacy({admin}){const[rows,setRows]=useState([]),[err,setErr]=useState('');async function load(){try{setRows(await api('/bills'))}catch(e){setErr(e.message)}}useEffect(()=>{load()},[]);async function submit(e){e.preventDefault();const fd=new FormData(e.target);try{await api('/bills',{method:'POST',body:fd});e.target.reset();load()}catch(e){setErr(e.message)}}return null}
function Users(){const[rows,setRows]=useState([]),[show,setShow]=useState(false),[edit,setEdit]=useState(null),[err,setErr]=useState('');async function load(){try{setRows(await api('/users'))}catch(e){setErr(e.message)}}useEffect(()=>{load()},[]);async function save(e){e.preventDefault();const f=Object.fromEntries(new FormData(e.target));try{if(edit)await api('/users/'+edit.id,{method:'PUT',body:JSON.stringify({...f,active:f.active==='true'})});else await api('/users',{method:'POST',body:JSON.stringify(f)});setShow(false);load()}catch(e){setErr(e.message)}}return <><div className="d-flex justify-content-between mb-3"><span className="text-muted">Create and manage portal access.</span><button className="btn btn-primary" onClick={()=>{setEdit(null);setShow(true)}}>＋ Add User</button></div>{err&&<div className="alert alert-danger">{err}</div>}<div className="card border-0 shadow-sm table-responsive"><table className="table mb-0"><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Status</th><th>Created</th><th></th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.name}</td><td>{r.email}</td><td><span className="badge bg-info text-dark">{r.role}</span></td><td>{r.active?'Active':'Inactive'}</td><td>{new Date(r.created_at).toLocaleDateString()}</td><td><button className="btn btn-sm btn-outline-primary" onClick={()=>{setEdit(r);setShow(true)}}>Edit</button></td></tr>)}</tbody></table></div>{show&&<div className="modal-backdrop-custom"><form className="form-modal" onSubmit={save}><div className="d-flex justify-content-between"><h5>{edit?'Edit User':'Create User'}</h5><button type="button" className="btn-close" onClick={()=>setShow(false)}/></div><label className="form-label mt-3">Full name</label><input name="name" className="form-control mb-3" defaultValue={edit?.name||''} required/><label className="form-label">Email</label><input name="email" type="email" className="form-control mb-3" defaultValue={edit?.email||''} required/><label className="form-label">Role</label><select name="role" className="form-select mb-3" defaultValue={edit?.role||'VIEWER'}><option>VIEWER</option><option>ADMIN</option></select>{!edit&&<><label className="form-label">Temporary password (8+ chars)</label><input name="password" type="password" minLength="8" className="form-control mb-3" required/></>}{edit&&<><label className="form-label">Status</label><select name="active" className="form-select mb-3" defaultValue={String(!!edit.active)}><option value="true">Active</option><option value="false">Inactive</option></select></>}<button className="btn btn-primary w-100">Save user</button></form></div>}</>}
function Logs(){const[rows,setRows]=useState([]),[err,setErr]=useState(''),[module,setModule]=useState('');useEffect(()=>{api('/audit-logs'+(module?'?module='+module:'')).then(setRows).catch(e=>setErr(e.message))},[module]);return <><div className="d-flex justify-content-between mb-3"><span className="text-muted">Who did what, and when. Latest 500 events.</span><select className="form-select" style={{maxWidth:220}} value={module} onChange={e=>setModule(e.target.value)}><option value="">All modules</option>{['EXPENSE','DONATION','USER','BILL','AUTH'].map(x=><option key={x}>{x}</option>)}</select></div>{err&&<div className="alert alert-danger">{err}</div>}<div className="card border-0 shadow-sm table-responsive"><table className="table mb-0"><thead><tr><th>Date & time</th><th>User</th><th>Action</th><th>Module</th><th>Record</th><th>Description</th><th>Details</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{new Date(r.created_at).toLocaleString()}</td><td>{r.user_name}<div className="small text-muted">{r.user_email}</div></td><td><span className="badge bg-secondary">{r.action}</span></td><td>{r.module}</td><td>#{r.record_id}</td><td>{r.description}</td><td><details><summary>View</summary><pre className="small">{JSON.stringify({old:r.old_values,new:r.new_values},null,2)}</pre></details></td></tr>)}</tbody></table></div></>}
export default App;
